name: Sync

on:
  push:
    branches:
      - main
  schedule:
    # every 12 hours
    - cron: '0 */12 * * *'


jobs:
  copy:
    strategy:
      matrix:
        version: [24.04, 26.04]
    runs-on: ubuntu-latest
    steps:
    - name: Install crane
      uses: imjasonh/setup-crane@v0.4
    - name: Copy image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        crane auth login index.docker.io -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        crane copy ubuntu:${{ matrix.version }} antrea/ubuntu:${{ matrix.version }}
